### ISSUE TITLE
Actualizar todas las fotos

### ISSUE THREAD

**Issue by sebasmos** [NASA-SpaceApps/nasapopayan.github.io#2]
actualizar fotos del evento/miembros

**Comment by Lau18ra** [comment]
Link de las fotos: https://unicaucaeduco-my.sharepoint.com/personal/dsgarcia_unicauca_edu_co/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2Fdsgarcia%5Funicauca%5Fedu%5Fco%2FDocuments%2FSpace%20Apps%202022%2FEvent

**Comment by Lau18ra** [comment]
Link de los embajadores (hasta el momento): https://drive.google.com/drive/folders/11OsUBksrcrWxG9G8rQnFWQztXZVFlWqF?usp=drive_link

**Comment by sebasmos** [comment]
done
